apiVersion: v1
kind: Secret
metadata:
   name: ssh-auth
type: kubernetes.io/basic-auth
data:
  ssh-privateKey: |
      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
      NhAAAAAwEAAQAAAYEAwdg+C7oQP9wyZPQa2tTmu6i8rvxgYZtJfeXw4k9GzUpkagxPd4fp
      JbuQM5PHM8rjuLqXrhX8FnHSwdzrXcO+h5GdN/vb8kwhrFBfmpNA66/CAennthow5uRnYc
      8NZkbtjpbmxWp61dZ/7xXbJO4vxYxI6l2/xVXbBpxcLZUY4T4XSWMBcQwC4G/wOWVTmQc/
      dGJymYKo9rsr+k6Qj5C272HzxoEs9N9L15mQpbzkSMCxv9jMmYrhwvBAuhOD8ChvL/FTBM
      0Y+8Wr5MNhq3Nn4X/BgxiPhYX8axpVt8zN0euH7fr9ZYOz9O2ERO0AlGEoLDUlIHxWztzZ
      kEEOuFnFZbrct2SI64dLp+ZIdv9imUeRvZ+WlnVD9mRoV8qAAzsESPXHMbZogRhUvcDC3G
      PpJLkH6iafy0WX+moqW6gqK+Bn5PleWxBYZXlp1p5VtBBFxDPP7GdkKlmcX+IaY7elcEj9
      coHb9ygMA9YuuMqKcSCaafDzzlB/Gmn7hDs2R7Z5AAAFiBAsy24QLMtuAAAAB3NzaC1yc2
      EAAAGBAMHYPgu6ED/cMmT0GtrU5ruovK78YGGbSX3l8OJPRs1KZGoMT3eH6SW7kDOTxzPK
      47i6l64V/BZx0sHc613DvoeRnTf72/JMIaxQX5qTQOuvwgHp57YaMObkZ2HPDWZG7Y6W5s
      VqetXWf+8V2yTuL8WMSOpdv8VV2wacXC2VGOE+F0ljAXEMAuBv8DllU5kHP3RicpmCqPa7
      K/pOkI+Qtu9h88aBLPTfS9eZkKW85EjAsb/YzJmK4cLwQLoTg/Aoby/xUwTNGPvFq+TDYa
      tzZ+F/wYMYj4WF/GsaVbfMzdHrh+36/WWDs/TthETtAJRhKCw1JSB8Vs7c2ZBBDrhZxWW6
      3LdkiOuHS6fmSHb/YplHkb2flpZ1Q/ZkaFfKgAM7BEj1xzG2aIEYVL3Awtxj6SS5B+omn8
      tFl/pqKluoKivgZ+T5XlsQWGV5adaeVbQQRcQzz+xnZCpZnF/iGmO3pXBI/XKB2/coDAPW
      LrjKinEgmmnw885Qfxpp+4Q7Nke2eQAAAAMBAAEAAAGBAKQmAvyZNjNtuvsEP016Jl1ZWV
      Zw/wkIn+ZN9nseGN21Fm07OXwGCmfaehVDGdgBAm+nCtTvZwZ2ortp4aIIJWrV4yXKUInQ
      8F7jvOG/uqUas5Y9RetOKIUNe4I2/KjUfUxW+trH/XbhanrCrk2KqceGsSRN+RwZRR1HAU
      PUUzpCAyQxA8KAIlt+TxW7eVxH5/MdfuAB5iTxgR84sm/wYwk5kF5Tewdto+LR9sxytXnq
      O1szMqb/FYinPJiV+A9BnNSoatTJrEDrx8JMEz+UHIjSdkp0iYRuyDqjoWzQBl5eDtxuPR
      hukM/ST0ZWAlS7Mggo449kEaXu7vjvGgNR42ktlPZemmS0MhijWDULjosY+MxjHAIsNp6g
      dsPQ292rOj26zM7L7+0gVESOC93spgEbHhLn0ZRCP1qtC7/hV/nfWc1Dnhk4IcTK/fYoRx
      61lzBpy/TK4fxsi6udSyz9Z5bXCym6ld+LeJoXvkznxdhCPJuCiIyAKmS58reAZLnUEQAA
      AMAmemHvy7xHPQojorykATxP/VSFJQR1fe4uTJGRMRsgtk5rJ8w5l0WAmmi97TAwR0eBE+
      mLaRv7k87KQXk1Ht5ZdmHlgePIrBJJpIO+LGQKYTl2ic9zWiQG88h1mCk5f+7nmwrjhGv8
      rQdBBM4yjK1KcFibryYELi3noRIk3L4AGwvAMBNrW/xV9ur0o9WGLic1bfU1KPj8rvBE78
      ee7ttH+ZXOL/XWrP4sBrYUJ3DdC1BG2McptA22ZVvh4ePF/Q8AAADBAOYaQfyBthZkEE/W
      qEf0zdYB0QLb07JQZnsMBaWMAb3//VuGIh3RPCMjLKjEb+M9DdBOenNUlk5sDZm9vJRpZO
      xVX5bA60D/GTDrnbr0U2S1wsSSdIKPU3RCpX0aZWr2yL6w1mDY9f/QgEM7oC6jvdzIY9AB
      Y0FW4TZYCmHdVpD9XxVNk2BPMOJ9V1cYOiq3htMlbw7gmT/ulqRibGKrOTGu+x0achWAQJ
      Fkk069+XDwtGAg2l+k7WwcM+T8MNa7BQAAAMEA16lRitYNqVOGscBReMDpPlEE1bWyZ9yt
      z9vZB50gnH7oR7a8KvcWfa3NUDvq7hHkeXl2jesvVb7ywfoMBLEgZFtyKIii56nfN5sLAy
      yz8QQ1O9Y0uLuyI3iQbgUUMb7Ia/ZtY1j+riv5yIkzul1NSvOevxoVv7byOwxqtYWBUd5M
      a0nkd2EPK4C5t+Mm/rL/OfjD8mez9e8VZZ8LJB4QeaJTesFmBkZ+tHKXqTefv3ayiXINUs
      lpACOX1dkeEq/lAAAAEnZhZ3JhbnRAa3ViZW1hc3Rlcg==
 
